version: '3.1'
services:

  mysql:
    image: mysql:8.0.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    networks: 
      - damp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: thisIsNotAGoodPassword
    ports:
      - 8080:80
    networks:
      - damp

  php:
    image: php:7.2.0-apache-stretch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    ports:
      - 80:80
    networks:
      - damp

networks:
  damp: