version: '3.1'
services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    networks: 
      - wordpress

  wordpress:
    image: wordpress:alpine
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: thisIsNotAGoodPassword
    networks: 
      - wordpress

networks: 
  wordpress: