version: '3.1'
services:

  java:
    image: openjdk
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    networks:
      - java-mysql
 
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    networks: 
      - java-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: thisIsNotAGoodPassword
    ports:
      - 8080:80
    networks:
      - java-mysql

networks:
  java-mysql