version: '3.1'
services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - damp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: thisIsNotAGoodPassword
    ports:
      - 8080:80
    networks:
      - damp

  php:
    image: php:apache
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./php:/var/www/html

networks:
  damp: