version: '3.1'
services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - wordpress

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./wordpress:/var/www/html
    networks: 
      - wordpress

networks: 
  wordpress: