version: '3.1'
services:

  mysql:
    image: mysql:8.0.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - wordpress

  wordpress:
    image: wordpress:4.9.1
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: thisIsNotAGoodPassword
    volumes:
      - ./wordpress-data:/var/www/html
    networks: 
      - wordpress

networks: 
  wordpress: